### ISSUE TITLE
GitHub Gives 2023 To-do List

### ISSUE THREAD

**Issue by demiwright** [demiwright/demiwright#4]
**[GitHub Gives Issue](https://github.com/github/social-impact/issues/1123)** 
**[Hubber Champions Repo](https://github.com/github/Hubber-Champions)**

# GitHub Gives 2023

**Description** - Hi Hubbers 👋
Social Impact is excited to launch the 6th year of GitHub Gives! If you're new to GitHub or not familiar with GitHub Gives, it's a 1 month long effort to raise funds for meaningful nonprofits that resonate with Hubbers. This year we want to engage as many Hubbers as possible to give during the month of October! While the suggested donation amount is $25, we also want to hear HOW you give. How you give your time, your talents, & your dedication to people and communities around you. With that, we are excited to announce that in addition to giving financially, we will also recognize tracked volunteer time this year.

## **Timeline**  
- [ ] Sept. 18th: Send toolkits & Comms plan to Hubber Champions
- [ ] Sept. 18th: Send all video submissions in to films team
- [ ] Sept. 19th: Confirm run of show & Send out to all involved
- [ ] Sept. 20th: Confirm Day of Learning Slides and Presentation
- [ ] Sept. 21st: Present DOL on how to use Benevity
- [ ] Sept. 28th: Slack post by Demi on #social-impact channel with promo video preview
- [ ] October 1: Shop Preorder shirts go on sale  
- [ ] October 2: Hub post by Sid: welcoming the campaign, kickoff reminder, video (which actually let's also play during the event to start maybe?), shop t-shirt opening
- [ ] October 3: Kick off event with LT & One Tree Planted
- [ ] October 9: Share team participation results
- [ ] October 10: Launch Trivia Question 1
- [ ] October 13: Announce Trivia Winner 1
- [ ] October 16: Share team participation results
- [ ] October 17: Hub post by TBC: halfway excitement upkeep/stories of giving/announcing a new volunteering activity?/reminder for t-shirts
- [ ] October 17: Launch Trivia Question 2
- [ ] October 20: Announce Trivia Winner 2
- [ ] October 23: Share team participation results
- [ ] October 23: Virtual Volunteer event this week - Goodera
- [ ] October 24: Launch Trivia Question 3:
- [ ] October 27: Announce Trivia Question 4
- [ ] October 27: Surprise Bonus Trivia Question
- [ ] October 30: Final Trivia Winner 
- [ ] October 30: Final push
- [ ] November 2: Hub Post by Demi: Closing out campaign and thank yous/final totals/stories of giving, volunteering

## 🌟Hubber Champions  🌟

- [ ] Hubber Champs comm plan and tool kits have been sent out
- [ ] Hubber Champs have zoom backgrounds available for team
- [ ]
